version: "3"
services:
  # ==================================================================================
  # A. Database Setup (Postgres + PgAdmin4)
  # ==================================================================================

  # ==========================
  # Keycloak Database
  # ==========================
  keycloak-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: keycloakDb
    volumes:
      - ./persistentStorage/data-keycloak-db:/var/lib/postgresql/data
    networks:
      - db-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d keycloakDb"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  # ==========================
  # Song Database
  # ==========================
  song-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: songDb
    volumes:
      - ./persistentStorage/data-song-db:/var/lib/postgresql/data
    networks:
      - db-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d songDb"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s


  # ==========================
  # pgAdmin4
  # ==========================
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5051:80"
    networks:
      - db-network

  # ==================================================================================
  # B. Object Storage (Minio, Minio Client)
  # ==================================================================================
  
  # ==========================
  # Minio
  # ==========================
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    command: server --console-address ":9001" /data
    volumes:
      - ./persistentStorage/data-minio:/data

  # ==========================
  # Minio Client
  # ==========================
  minio-client:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://host.docker.internal:9000 admin admin123 &&
      /usr/bin/mc mb myminio/state &&
      /usr/bin/mc mb myminio/object;
      exit 0;
      "

  # ==================================================================================
  # C. OAuth (KeyCloak)
  # ==================================================================================
  
  # ==========================
  # Keycloak
  # ==========================
  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    depends_on:
      keycloak-db:
        condition: service_healthy
    container_name: keycloak
    ports:
      - "8443:8443"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      KC_HOSTNAME: localhost
    volumes:
      - ./configurationFiles/keycloakConfigs/server.keystore:/opt/keycloak/conf/server.keystore
      - ./configurationFiles/keycloakConfigs/keycloak-apikeys-1.0.1.jar:/opt/keycloak/providers/keycloak-apikeys.jar
      - ./configurationFiles/keycloakConfigs/myrealm-realm.json:/opt/keycloak/data/import/myrealm-realm.json
      - ./configurationFiles/keycloakConfigs/myrealm-users-0.json:/opt/keycloak/data/import/myrealm-users-0.json
    networks:
      - db-network
    command: >
      start
      --import-realm
      --db=postgres
      --db-url=jdbc:postgresql://keycloak-db:5432/keycloakDb
      --db-username=admin
      --db-password=admin123
      --https-key-store-file=/opt/keycloak/conf/server.keystore
      --https-key-store-password=password

# ==========================
# Networks
# ==========================
networks:
  db-network: